In [23]:
import pandas as pd
from datetime import date, time, datetime, timedelta

In [6]:
df=pd.read_csv('cuentas_credicel.csv', encoding='latin')
df

/var/folders/ym/rbj3xt1s2z99f7dbk593w20h0000gn/T/ipykernel_84011/2423771377.py:1: DtypeWarning: Columns (26,31,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('cuentas_credicel.csv', encoding='latin')

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,3,HDNAWQ3A,30,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,26.0,NaN
1,4,M418YNR4,33,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,13.0,NaN
2,5,SZ7V3NZT,37,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,0.00,0.00,0.0,0,0.0,NaN,NaN,74,NaN,NaN
3,6,9I08UIQZ,38,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,13.0,NaN
4,7,JMF4LKYU,44,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,0.00,0.00,0.0,NaN,NaN,74,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22730,22967,92KQVRIX,96502,18/04/2023 18:45,Motorola,Moto E13,26S,3349.0,297.0,0.0,...,27.40,-1.13,0.0,0,"K0,J0,D8,E2",0,97880.0,NaN,NaN,NaN
22731,22968,NWB2EA8J,96479,18/04/2023 18:46,Motorola,Moto E22i,26S,4100.0,1209.0,0.0,...,19.00,7.48,0.0,0,"K0,J0,D8,E2",0,37295.0,NaN,NaN,NaN
22732,22969,VDTRJ2W6,96442,18/04/2023 18:47,Samsung,A13,26S,4849.0,1152.0,0.0,...,26.65,0.75,0.0,0,"K0,D7,F7,D8",0,20210.0,NaN,NaN,NaN
22733,22970,PETLF56C,96536,18/04/2023 18:49,Samsung,A53 5G,39S,9799.0,2799.0,0.0,...,-17.35,-0.14,0.0,0,"J0,G1,E0,E2",0,78434.0,NaN,NaN,NaN
22734,22971,2CI4N2WS,96534,18/04/2023 18:49,Samsung,A22 5G,26S,5399.0,1086.0,0.0,...,21.80,-2.88,0.0,0,C2,0,43800.0,NaN,NaN,NaN

In [61]:
nuevodf=df.iloc[ :, [1] + list(range(3, 33))] 
nuevodf=df[(df["marca"] == "ALCATEL ") | (df["marca"] == "MOTOROLA") | (df["marca"]=="NOKIA") | (df["marca"]=="ZTE") | (df["marca"]=="SAMSUNG")]
nuevodf= df[(df["enganche"] >= 500) &(df["enganche"]<=2000)]
nuevodf =df[~(df["riesgo"] == "Cancelado") & ~(df["riesgo"]== "Fraude")]
nuevodf= df[df['fecha']>("15/11/2021")]
nuevodf=nuevodf.iloc[::4, :]
nuevodf

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
12,15,BFXA3OX9,77,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,26.0,NaN
16,19,X53IWV9M,83,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,13.0,NaN
20,23,C9LVYPGM,101,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.00,625.0,0.0,...,0.00,0.00,0.0,NaN,NaN,74,NaN,NaN,NaN,NaN
24,28,BWRZ9ZRG,112,20/11/2021 14:00,MOTOROLA,MOTOROLA LTE XT2053-5 E6I Gris,13S,2999.00,900.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,13.0,NaN
28,32,74DZR6G2,127,23/11/2021 15:17,MOTOROLA,LTE XT2097-12 E7I POWER Naranja,26S,3299.00,990.0,0.0,...,NaN,0.00,0.0,0,0.0,0,NaN,NaN,26.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22717,22954,9Q60ZHIH,96450,18/04/2023 16:53,SAMSUNG,A03 4+64GB ROJO B,39S,3793.85,948.0,0.0,...,10.25,3.99,0.0,0,"D7,K0,F7,D8",0,93557.0,NaN,NaN,NaN
22721,22958,O02NOS0D,96477,18/04/2023 17:04,Samsung,A04E,26S,3149.00,810.0,200.0,...,4.45,4.73,0.0,0,"K0,J0,D7,G1",0,97430.0,NaN,NaN,NaN
22725,22962,8OLERMPL,95675,18/04/2023 17:23,ZTE,BLADE A52 LITE 2+32GB VERDE B,13S,2572.83,607.0,0.0,...,2.00,3.60,0.0,0,"G1,E0,E2,J0",0,72230.0,NaN,NaN,NaN
22729,22966,MEQRYKUR,96508,18/04/2023 17:45,Samsung,A53 5G,26S,8500.00,4500.0,0.0,...,26.25,3.57,0.0,0,C2,0,73300.0,NaN,NaN,NaN
22733,22970,PETLF56C,96536,18/04/2023 18:49,Samsung,A53 5G,39S,9799.00,2799.0,0.0,...,-17.35,-0.14,0.0,0,"J0,G1,E0,E2",0,78434.0,NaN,NaN,NaN

In [62]:
nuevodf.to_csv("filtros_OmarQuinn.csv")

Ejercicio 2

In [ ]:
df2=pd.read_csv("cuentas_credicel.csv", encoding="latin")
df2

In [17]:
data=df2.copy()

In [ ]:
fechas=["fecha_ultimo_pago", "fecha_pago_proximo","fecha"]
for col in fechas:
    data[col] = data[col].fillna(pd.to_datetime("01/01/2030", format="%d/%m/%Y"))

  fecha_ultimo_pago fecha_pago_proximo      fecha
0        2030-01-01         2030-01-01 2030-01-01
1        2030-01-01         2030-01-01 2030-01-01
2        2030-01-01         2030-01-01 2030-01-01
3        2030-01-01         2030-01-01 2030-01-01
4        2030-01-01         2030-01-01 2030-01-01

In [34]:
columnas_objetos = data.select_dtypes(include=['object']).columns
for col in columnas_objetos:
    data[col] = data[col].fillna("Sin registro")

In [39]:
columnas_numericos=data.select_dtypes(include=['int64', 'float64']).columns
for col in columnas_numericos:
    data[col] = data[col].fillna("Promedio")
    
valores_nulos=data.isnull().sum()
valores_nulos

folio                 0
tag                   0
folio_solicitud       0
fecha                 0
marca                 0
modelo                0
plazo                 0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
agente_venta          0
dis_venta             0
status                0
fraude                0
empresa               0
inversion             0
pagos_realizados      0
reautorizacion        0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
porc_enganche         0
porc_tasa             0
score_buro            0
razones_buro          0
semana_actual         0
codigo_postal         0
Unnamed: 33           0
Unnamed: 34           0
Unnamed: 35           0
Unnamed: 36           0
dtype: int64

In [37]:
data.to_csv("Valores_Nulos_OmarQuinn.csv")

Ejercicio 3

In [40]:
dataframe = pd.read_csv("Valores_Nulos_OmarQuinn.csv", encoding= "latin")

/var/folders/ym/rbj3xt1s2z99f7dbk593w20h0000gn/T/ipykernel_84011/1335036932.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv("Valores_Nulos_OmarQuinn.csv", encoding= "latin")

In [41]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 38 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          22735 non-null  int64
 1   folio               22735 non-null  int64
 2   tag                 22735 non-null  object
 3   folio_solicitud     22735 non-null  int64
 4   fecha               22735 non-null  object
 5   marca               22735 non-null  object
 6   modelo              22735 non-null  object
 7   plazo               22735 non-null  object
 8   precio              22735 non-null  float64
 9   enganche            22735 non-null  float64
 10  descuento           22735 non-null  float64
 11  semana              22735 non-null  int64
 12  monto_financiado    22735 non-null  float64
 13  costo_total         22735 non-null  int64
 14  monto_accesorios    22735 non-null  float64
 15  agente_venta        22735 non-null  object
 16  dis_venta           22735 non-null  object
 17  status              22735 non-null  int64
 18  fraude              22735 non-null  int64
 19  empresa             22735 non-null  object
 20  inversion           22735 non-null  int64
 21  pagos_realizados    22735 non-null  int64
 22  reautorizacion      22735 non-null  int64
 23  fecha_ultimo_pago   22735 non-null  object
 24  fecha_pago_proximo  22735 non-null  object
 25  status_cuenta       22735 non-null  object
 26  puntos              22735 non-null  object
 27  riesgo              22735 non-null  object
 28  porc_enganche       22735 non-null  object
 29  porc_tasa           22735 non-null  float64
 30  score_buro          22735 non-null  float64
 31  razones_buro        22735 non-null  object
 32  semana_actual       22735 non-null  object
 33  codigo_postal       22735 non-null  object
 34  Unnamed: 33         22735 non-null  object
 35  Unnamed: 34         22735 non-null  object
 36  Unnamed: 35         22735 non-null  object
 37  Unnamed: 36         22735 non-null  object
dtypes: float64(7), int64(10), object(21)
memory usage: 6.6+ MB

In [ ]:
cuantitativas = dataframe.iloc[:, [0]+[1]+[3]+list(range(8,15))+[17]+[18]+[20]+[21]+[22]+[29]+[30]]
cualitativas = dataframe.iloc[:, list(range(4,8))+[15]+[16]+[19]+list(range(23,29))+list(range(31,38))]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   fecha               22735 non-null  object
 1   marca               22735 non-null  object
 2   modelo              22735 non-null  object
 3   plazo               22735 non-null  object
 4   agente_venta        22735 non-null  object
 5   dis_venta           22735 non-null  object
 6   empresa             22735 non-null  object
 7   fecha_ultimo_pago   22735 non-null  object
 8   fecha_pago_proximo  22735 non-null  object
 9   status_cuenta       22735 non-null  object
 10  puntos              22735 non-null  object
 11  riesgo              22735 non-null  object
 12  porc_enganche       22735 non-null  object
 13  razones_buro        22735 non-null  object
 14  semana_actual       22735 non-null  object
 15  codigo_postal       22735 non-null  object
 16  Unnamed: 33         22735 non-null  object
 17  Unnamed: 34         22735 non-null  object
 18  Unnamed: 35         22735 non-null  object
 19  Unnamed: 36         22735 non-null  object
dtypes: object(20)
memory usage: 3.5+ MB

In [45]:
y=cuantitativas
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

Limite superior permitido Unnamed: 0           31056.520563
folio                31323.107698
folio_solicitud     127723.906961
precio                8081.558082
enganche              2356.496845
descuento              478.215020
semana                 541.287392
monto_financiado      6366.317810
costo_total          12857.588246
monto_accesorios       191.260880
status                   2.611178
fraude                   0.864131
inversion                1.511599
pagos_realizados        39.306132
reautorizacion           0.578086
porc_tasa               24.630537
score_buro              13.931194
dtype: float64
Limite inferior permitido Unnamed: 0          -8322.520563
folio               -8301.055796
folio_solicitud    -36023.715538
precio                -87.484900
enganche             -503.622066
descuento            -321.263535
semana                -65.792692
monto_financiado     -214.044583
costo_total         -1458.203597
monto_accesorios     -164.333344
status                 -0.100423
fraude                 -0.714494
inversion              -1.038408
pagos_realizados      -18.944575
reautorizacion         -0.509998
porc_tasa             -21.606103
score_buro            -14.442358
dtype: float64

In [46]:
data3= cuantitativas[(y<=Limite_Superior)&(y>=Limite_Inferior)]
data3

,Unnamed: 0,folio,folio_solicitud,precio,enganche,descuento,semana,monto_financiado,costo_total,monto_accesorios,status,fraude,inversion,pagos_realizados,reautorizacion,porc_tasa,score_buro
0,0,3,30,1949.0,780.0,0.0,81.0,1169.0,2106.0,0.0,2.0,0.0,0,0.0,0.0,0.00,0.0
1,1,4,33,2999.0,1050.0,0.0,225.0,1949.0,2925.0,0.0,2.0,0.0,0,0.0,0.0,0.00,0.0
2,2,5,37,1959.0,490.0,0.0,170.0,1469.0,2210.0,0.0,NaN,0.0,0,0.0,0.0,0.00,0.0
3,3,6,38,1959.0,490.0,0.0,170.0,1469.0,2210.0,0.0,2.0,0.0,0,0.0,0.0,0.00,0.0
4,4,7,44,4299.0,1075.0,0.0,178.0,3224.0,6942.0,0.0,1.0,0.0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22730,22730,22967,96502,3349.0,297.0,0.0,211.0,3052.0,5486.0,0.0,1.0,0.0,0,0.0,0.0,-1.13,0.0
22731,22731,22968,96479,4100.0,1209.0,0.0,200.0,2891.0,5200.0,0.0,1.0,0.0,0,0.0,0.0,7.48,0.0
22732,22732,22969,96442,4849.0,1152.0,0.0,256.0,3697.0,6656.0,0.0,1.0,0.0,0,0.0,0.0,0.75,0.0
22733,22733,22970,96536,NaN,NaN,0.0,386.0,NaN,NaN,0.0,1.0,0.0,0,0.0,0.0,-0.14,0.0
22734,22734,22971,96534,5399.0,1086.0,0.0,299.0,4313.0,7774.0,0.0,1.0,0.0,1,0.0,0.0,-2.88,0.0

In [47]:
valores_nulos=data3.isnull().sum()
valores_nulos

Unnamed: 0             0
folio                  0
folio_solicitud        0
precio               110
enganche             292
descuento             17
semana               362
monto_financiado     182
costo_total          290
monto_accesorios     617
status               154
fraude              1701
inversion              0
pagos_realizados     184
reautorizacion       774
porc_tasa            899
score_buro           582
dtype: int64

In [49]:
data_clean=data3.copy()
data_clean=data_clean.fillna(round(data3.mean(),1))

valores_nulos=data_clean.isnull().sum()
valores_nulos

Unnamed: 0          0
folio               0
folio_solicitud     0
precio              0
enganche            0
descuento           0
semana              0
monto_financiado    0
costo_total         0
monto_accesorios    0
status              0
fraude              0
inversion           0
pagos_realizados    0
reautorizacion      0
porc_tasa           0
score_buro          0
dtype: int64

In [ ]:
y=cuantitativas

percentile25=y.quantile(0.25) 
percentile75=y.quantile(0.75) 
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido Unnamed: 0           34101.00
folio                34333.50
folio_solicitud     139392.00
precio                7674.00
enganche              1841.75
descuento              500.00
semana                 457.50
monto_financiado      5703.00
costo_total          11108.50
monto_accesorios         0.00
status                   1.00
fraude                   0.00
inversion                0.00
pagos_realizados        34.50
reautorizacion           0.00
porc_tasa                0.00
score_buro               0.00
dtype: float64
Limite inferior permitido Unnamed: 0         -11367.00
folio              -11290.50
folio_solicitud    -49692.00
precio                274.00
enganche             -104.25
descuento            -300.00
semana                 -2.50
monto_financiado      359.00
costo_total          -175.50
monto_accesorios        0.00
status                  1.00
fraude                  0.00
inversion               0.00
pagos_realizados      -17.50
reautorizacion          0.00
porc_tasa               0.00
score_buro              0.00
dtype: float64

In [51]:
data3_iqr= cuantitativas[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

,Unnamed: 0,folio,folio_solicitud,precio,enganche,descuento,semana,monto_financiado,costo_total,monto_accesorios,status,fraude,inversion,pagos_realizados,reautorizacion,porc_tasa,score_buro
0,0,3,30,1949.0,780.0,0.0,81.0,1169.0,2106.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,1,4,33,2999.0,1050.0,0.0,225.0,1949.0,2925.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,2,5,37,1959.0,490.0,0.0,170.0,1469.0,2210.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,3,6,38,1959.0,490.0,0.0,170.0,1469.0,2210.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
4,4,7,44,4299.0,1075.0,0.0,178.0,3224.0,6942.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22730,22730,22967,96502,3349.0,297.0,0.0,211.0,3052.0,5486.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0
22731,22731,22968,96479,4100.0,1209.0,0.0,200.0,2891.0,5200.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0
22732,22732,22969,96442,4849.0,1152.0,0.0,256.0,3697.0,6656.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0
22733,22733,22970,96536,NaN,NaN,0.0,386.0,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0
22734,22734,22971,96534,5399.0,1086.0,0.0,299.0,4313.0,7774.0,0.0,1.0,0.0,NaN,0.0,0.0,NaN,0.0

In [55]:
data4_iqr=data3_iqr.copy()
data4_iqr=data4_iqr.fillna(round(data3_iqr.median(),1))
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

Unnamed: 0             0
folio                  0
folio_solicitud        0
precio               309
enganche             871
descuento              0
semana               946
monto_financiado     497
costo_total          787
monto_accesorios    1854
status              5649
fraude              1701
inversion           5379
pagos_realizados     534
reautorizacion       774
porc_tasa           3044
score_buro          1806
dtype: int64

In [54]:
Datos_limpios = pd.concat([cualitativas, data4_iqr], axis=1)
valores_nulos=Datos_limpios.isnull().sum()
valores_nulos

fecha                 0
marca                 0
modelo                0
plazo                 0
agente_venta          0
dis_venta             0
empresa               0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
porc_enganche         0
razones_buro          0
semana_actual         0
codigo_postal         0
Unnamed: 33           0
Unnamed: 34           0
Unnamed: 35           0
Unnamed: 36           0
Unnamed: 0            0
folio                 0
folio_solicitud       0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
status                0
fraude                0
inversion             0
pagos_realizados      0
reautorizacion        0
porc_tasa             0
score_buro            0
dtype: int64

In [56]:
Datos_limpios.to_csv("Ejercicio3_OmarQuinn.csv")